### ISSUE TITLE
Implement driver for AD2S1210

### ISSUE THREAD

**Issue by pamolloy** [analogdevicesinc/no-OS#1836]
Implement a no-OS driver for the AD2S1210.

Note that the ZedBoard can also be used for development if the K1 has not yet arrived.

## Tasks

- [ ] If not already setup, setup hardware for testing
- [ ] Implement driver for AD2S1210
- [ ] Add documentation based on https://github.com/analogdevicesinc/no-OS/blob/master/drivers/accel/adxl355/README.rst
- [ ] Test driver on above hardware
- [ ] Push code to no-OS repository to run automated testing
- [ ] Open PR in no-OS repository for code review
- [ ] Update to match Linux kernel driver

## Dependencies

- adi-ses/sea-misc/issues/2
- analogdevicesinc/hdl/issues/1147 (optional)
- adi-ses/sea-misc/issues/4
- adi-ses/sea-misc/issues/16
- adi-ses/sea-misc/issues/11
