### ISSUE TITLE
Extend support for AD40xx with variable sample frequency

### ISSUE THREAD

**Issue by pamolloy** [analogdevicesinc/no-OS#1846]
The `ad400x.c` driver currently does not support variable sampling frequency. See [ad469x.c](https://github.com/analogdevicesinc/no-OS/blob/master/drivers/adc/ad469x/ad469x.c) and [ad463x.c](https://github.com/analogdevicesinc/no-OS/blob/master/drivers/adc/ad463x/ad463x.c) as examples.

Note that all FPGA specific calls should be wrapped by `!defined(USE_STANDARD_SPI)`.

Note that for K1 support the frequency is defined in [`app_config_mbed.h`](https://github.com/analogdevicesinc/precision-converters-firmware/blob/main/projects/ad4696_iio/app/app_config_mbed.h#L60) and assigned in [`app_config.c`](https://github.com/analogdevicesinc/precision-converters-firmware/blob/main/projects/ad4696_iio/app/app_config.c#L58) in the precision-converters-firmware repo.

## Hardware

- [ ] MX1002 → EVAL-AD4000FMCZ → ZedBoard
- [ ] MX1002 → EVAL-AD4001FMCZ → ZedBoard
- [ ] MX1002 → EVAL-AD4002FMCZ → ZedBoard
- [ ] MX1002 → EVAL-AD4003FMCZ → ZedBoard
- [ ] MX1002 → EVAL-AD4020FMCZ → ZedBoard
- [ ] MX1002 → EVAL-ADAQ4001PMDZ → EVAL-PMD-IB1Z → ZedBoard
- [ ] MX1002 → EVAL-ADAQ4003PMDZ → EVAL-PMD-IB1Z → ZedBoard

Maximum supported sampling frequencies (e.g. see [`AD4630_MAX_RATE`](https://github.com/analogdevicesinc/linux/blob/master/drivers/iio/adc/ad4630.c#L95)):

- AD4001: 2.0 MSPS
- AD4005: 1.0 MSPS
- AD4002: 2.0 MSPS
- AD4006: 1.0 MSPS
- AD4010: 0.5 MSPS
- AD4000: 2.0 MSPS
- AD4004: 1.0 MSPS
- AD4008: 0.5 MSPS
- AD4003: 2.0 MSPS
- AD4007: 1.0 MSPS
- AD4011: 0.5 MSPS
- AD4020: 1.8 MSPS
- AD4021: 1.0 MSPS
- AD4022: 0.5 MSPS

## Existing implementation

```
drivers/adc/ad400x/ad400x.c
drivers/adc/ad400x/ad400x.h
projects/ad400x-fmcz/src/ad400x_fmcz.c
```

```
const uint16_t ad400x_device_resol[] = {
	[ID_AD4003] = 18,
	[ID_AD4007] = 18,
	[ID_AD4011] = 18,
	[ID_AD4020] = 20,
	[ID_ADAQ4003] = 18
};
```

## Tasks

- [ ] Update [ADI wiki](https://wiki.analog.com/resources/eval/user-guides/ad400x) to reflect above changes
- [ ] Update driver to request sampling frequency in FPGA from userspace. This will be done by configuring a PWM clock, which will corresponding to a sampling rate
- [ ] Update driver to read sampling frequency from the FPGA, which may not match the requested sampling frequency
- [ ] Check requested sampling frequency against the maximum frequency for a given part
- [ ] Test EVAL-AD4000FMCZ and add `ID_AD4000`
- [ ] Test EVAL-AD4001FMCZ and add `ID_AD4001`
- [ ] Test EVAL-AD4002FMCZ and add `ID_AD4002`
- [ ] Test EVAL-ADAQ4001PMDZ and add `ID_ADAQ4001`

## Dependencies

- analogdevicesinc/hdl/issues/1152
https://github.com/analogdevicesinc/no-OS/blob/master/drivers/adc/ad400x/ad400x.c
